package model

import (
	"context"
	"iter"

	"github.com/hupe1980/agentmesh/pkg/message"
	"github.com/hupe1980/agentmesh/pkg/tool"
)

// TokenLogprob represents log probability information for a single token.
type TokenLogprob struct {
	// Token is the actual token string
	Token string

	// Logprob is the log probability of this token
	Logprob float64

	// Bytes is the byte representation of the token (optional)
	Bytes []byte

	// TopLogprobs contains alternative tokens and their log probabilities.
	// Useful for understanding what other tokens the model considered.
	TopLogprobs []TopLogprob
}

// TopLogprob represents an alternative token choice with its probability.
type TopLogprob struct {
	Token   string
	Logprob float64
	Bytes   []byte
}

// Logprobs contains log probability information for generated tokens.
// This data is useful for understanding model confidence and decision-making.
type Logprobs struct {
	// Content contains log probabilities for each generated token
	Content []TokenLogprob
}

// Request contains all parameters for a model generation request.
// This struct allows passing messages, tools, and other options in a single call.
type Request struct {
	// Messages is the conversation history to send to the model
	Messages []message.Message

	// Tools is an optional list of tools the model can call during generation.
	// Only relevant if Capabilities().Tools is true.
	Tools []tool.Tool

	// SystemPrompt is an optional system instruction sent with this request.
	// When provided, it will be prepended to the messages (or sent via provider-specific
	// system parameter). This is sent per-request and not stored in conversation history,
	// making it more token-efficient than adding a system message to the state.
	//
	// If empty, only the messages from the Messages field are used.
	SystemPrompt string

	// Schema is an optional JSON schema for structured output generation.
	// When provided (and Capabilities().StructuredOutput is true), the model will
	// be constrained to generate valid JSON matching this schema.
	// The schema should be a map[string]any representing a JSON Schema definition.
	//
	// Example:
	//  req.Schema = map[string]any{
	//      "type": "object",
	//      "properties": map[string]any{
	//          "name": map[string]any{"type": "string"},
	//          "age":  map[string]any{"type": "integer"},
	//      },
	//      "required": []string{"name", "age"},
	//  }
	Schema map[string]any

	// Stream indicates whether to use streaming mode.
	// When true, Generate() will yield incremental chunks with Partial=true.
	// When false, Generate() will yield only the final complete response.
	Stream bool

	// Metadata contains additional request-specific parameters.
	// Use this for provider-specific options not covered by standard fields.
	Metadata map[string]any
}

// Response wraps the message with additional metadata from model generation.
// This provides a clean way to access reasoning, usage statistics, and other
// model-specific information without polluting the message structure.
type Response struct {
	// Message is the actual message content generated by the model
	Message message.Message

	// Reasoning contains the model's internal reasoning/thinking process.
	// This is populated by reasoning-capable models like:
	// - OpenAI o1/o3 (reasoning_content)
	// - Google Gemini 2.0 Flash (thinking mode)
	// - Anthropic Claude 3.5+ (extended thinking)
	// Empty for models without native reasoning support.
	Reasoning string

	// FinishReason indicates why the model stopped generating tokens.
	// Common values: "stop" (natural completion), "length" (max tokens),
	// "tool_calls" (model wants to call a tool), "content_filter" (content policy).
	// Empty string if not provided by the model.
	FinishReason string

	// Logprobs contains the log probabilities of generated tokens.
	// Useful for understanding model confidence and alternative token choices.
	// Nil if log probabilities were not requested or not supported.
	Logprobs *Logprobs

	// Usage provides token consumption information for cost tracking and observability
	Usage *UsageInfo

	// Metadata contains additional model-specific information
	Metadata map[string]any

	// Partial indicates whether this is an incremental streaming chunk (true)
	// or the final complete response (false).
	// For streaming mode: true for all chunks except the last one.
	// For blocking mode: always false (single complete response).
	// Useful for UI state management (e.g., showing spinners until !Partial).
	Partial bool
}

// UsageInfo tracks token consumption for observability and cost tracking.
type UsageInfo struct {
	// PromptTokens is the number of tokens in the input prompt
	PromptTokens int

	// CompletionTokens is the number of tokens in the generated completion
	CompletionTokens int

	// ReasoningTokens is the number of tokens used for internal reasoning.
	// Only applicable for reasoning-capable models (e.g., OpenAI o1/o3).
	// Zero for models without separate reasoning token tracking.
	ReasoningTokens int

	// TotalTokens is the sum of prompt, completion, and reasoning tokens
	TotalTokens int
}

// Capabilities describes the features and limitations of a model.
// This allows callers to discover what a model supports before using it.
type Capabilities struct {
	// Streaming indicates if the model supports streaming responses.
	// When true, Generate() will yield incremental chunks with Partial=true.
	Streaming bool

	// Tools indicates if the model supports tool/function calling.
	// When true, you can include tools in Request.Tools.
	Tools bool

	// StructuredOutput indicates if the model supports JSON schema-constrained output.
	// When true, you can provide a schema in Request.Metadata["schema"].
	StructuredOutput bool

	// NativeReasoning indicates if the model exposes its internal reasoning process.
	// When true, Response.Reasoning will be populated with the model's thinking.
	// Examples: OpenAI o1/o3, Gemini 2.0 thinking mode, Claude extended thinking.
	NativeReasoning bool

	// Logprobs indicates if the model can provide token-level log probabilities.
	// When true, Response.Logprobs may be populated (if explicitly requested).
	Logprobs bool

	// Vision indicates if the model can process image inputs.
	// When true, you can include message.ImagePart in your messages.
	Vision bool

	// Audio indicates if the model can process audio inputs.
	Audio bool

	// MaxContextTokens is the maximum context window size in tokens.
	// This is the total budget for input + output tokens.
	// Zero means unknown or unlimited.
	MaxContextTokens int

	// MaxOutputTokens is the maximum number of tokens the model can generate.
	// This may be constrained by configuration or model architecture.
	// Zero means unknown or uses default limits.
	MaxOutputTokens int

	// SupportedModalities lists the input types the model accepts.
	// Common values: "text", "image", "audio", "video"
	SupportedModalities []string
}

// Model defines the contract for language model backends using Go 1.23+ iterators.
// The unified Generate method supports both streaming and blocking consumption patterns.
type Model interface {
	// Generate performs a request that yields Response chunks as an iterator.
	// For streaming, iterate over all chunks to get incremental updates.
	// For blocking, consume only the final response using Last() or similar helpers.
	//
	// ERROR HANDLING:
	//   - Fatal errors (API failures, context canceled, invalid input) are returned
	//     in the second return value (err) as per Go iterator convention
	//   - When err != nil, iteration stops and no more responses are yielded
	//   - Response content is always valid when err == nil
	//
	// Streaming usage:
	//   req := &model.Request{
	//       Messages: messages,
	//       Tools:    myTools,
	//   }
	//   for resp, err := range model.Generate(ctx, req) {
	//       if err != nil {
	//           return fmt.Errorf("generation failed: %w", err)
	//       }
	//       fmt.Print(message.Stringify(resp.Message)) // Process each chunk
	//   }
	//
	// Blocking usage (helper required):
	//   req := &model.Request{Messages: messages}
	//   resp, err := Last(model.Generate(ctx, req))
	//   if err != nil {
	//       return fmt.Errorf("generation failed: %w", err)
	//   }
	//   fmt.Println(message.Stringify(resp.Message)) // Process final message
	//   fmt.Println("Reasoning:", resp.Reasoning) // Access native reasoning
	//   fmt.Println("Finish reason:", resp.FinishReason) // Why generation stopped
	//   fmt.Printf("Tokens used: %d\n", resp.Usage.TotalTokens)
	//   if resp.Logprobs != nil {
	//       // Access token probabilities for confidence analysis
	//   }
	//
	// The iterator will yield:
	// - Multiple responses with incremental content (streaming mode)
	// - A single final response (blocking mode)
	//
	// Context cancellation is respected and will stop iteration.
	Generate(ctx context.Context, req *Request) iter.Seq2[*Response, error]

	// Capabilities returns the features and limitations of this model.
	// Use this to discover what the model supports before attempting to use
	// optional features like tools, structured output, or native reasoning.
	//
	// Example:
	//   caps := model.Capabilities()
	//   if caps.Tools {
	//       req.Tools = myTools
	//   }
	//   if caps.NativeReasoning {
	//       // Model will populate Response.Reasoning automatically
	//   }
	Capabilities() Capabilities
}

// Last consumes an iterator and returns only the final response and error.
// This is the standard way to use Generate() in blocking/non-streaming mode.
//
// Example:
//
//	req := &model.Request{Messages: messages}
//	resp, err := model.Last(model.Generate(ctx, req))
//	if err != nil {
//	    return err
//	}
//	fmt.Println(message.Stringify(resp.Message))
//	if resp.Reasoning != "" {
//	    fmt.Println("Reasoning:", resp.Reasoning)
//	}
func Last(seq iter.Seq2[*Response, error]) (*Response, error) {
	var lastResp *Response
	var lastErr error

	for resp, err := range seq {
		lastResp = resp
		if err != nil {
			lastErr = err
			break
		}
	}

	return lastResp, lastErr
}

// Collect gathers all responses from an iterator into a slice.
// The final error (if any) is returned separately.
//
// Example:
//
//	req := &model.Request{Messages: messages}
//	responses, err := model.Collect(model.Generate(ctx, req))
//	if err != nil {
//	    return err
//	}
//	for _, resp := range responses {
//	    fmt.Print(message.Stringify(resp.Message))
//	}
func Collect(seq iter.Seq2[*Response, error]) ([]*Response, error) {
	responses := make([]*Response, 0)
	var lastErr error

	for resp, err := range seq {
		if err != nil {
			lastErr = err
			break
		}
		responses = append(responses, resp)
	}

	return responses, lastErr
}
