package model

import (
	"context"
	"iter"

	"github.com/hupe1980/agentmesh/pkg/message"
	"github.com/hupe1980/agentmesh/pkg/tool"
)

// TokenLogprob represents log probability information for a single token.
type TokenLogprob struct {
	// Token is the actual token string
	Token string

	// Logprob is the log probability of this token
	Logprob float64

	// Bytes is the byte representation of the token (optional)
	Bytes []byte

	// TopLogprobs contains alternative tokens and their log probabilities.
	// Useful for understanding what other tokens the model considered.
	TopLogprobs []TopLogprob
}

// TopLogprob represents an alternative token choice with its probability.
type TopLogprob struct {
	Token   string
	Logprob float64
	Bytes   []byte
}

// Logprobs contains log probability information for generated tokens.
// This data is useful for understanding model confidence and decision-making.
type Logprobs struct {
	// Content contains log probabilities for each generated token
	Content []TokenLogprob
}

// Response wraps the message with additional metadata from model generation.
// This provides a clean way to access reasoning, usage statistics, and other
// model-specific information without polluting the message structure.
type Response struct {
	// Message is the actual message content generated by the model
	Message message.Message

	// Reasoning contains the model's internal reasoning/thinking process.
	// This is populated by reasoning-capable models like:
	// - OpenAI o1/o3 (reasoning_content)
	// - Google Gemini 2.0 Flash (thinking mode)
	// - Anthropic Claude 3.5+ (extended thinking)
	// Empty for models without native reasoning support.
	Reasoning string

	// FinishReason indicates why the model stopped generating tokens.
	// Common values: "stop" (natural completion), "length" (max tokens),
	// "tool_calls" (model wants to call a tool), "content_filter" (content policy).
	// Empty string if not provided by the model.
	FinishReason string

	// Logprobs contains the log probabilities of generated tokens.
	// Useful for understanding model confidence and alternative token choices.
	// Nil if log probabilities were not requested or not supported.
	Logprobs *Logprobs

	// Usage provides token consumption information for cost tracking and observability
	Usage *UsageInfo

	// Metadata contains additional model-specific information
	Metadata map[string]any
}

// UsageInfo tracks token consumption for observability and cost tracking.
type UsageInfo struct {
	// PromptTokens is the number of tokens in the input prompt
	PromptTokens int

	// CompletionTokens is the number of tokens in the generated completion
	CompletionTokens int

	// ReasoningTokens is the number of tokens used for internal reasoning.
	// Only applicable for reasoning-capable models (e.g., OpenAI o1/o3).
	// Zero for models without separate reasoning token tracking.
	ReasoningTokens int

	// TotalTokens is the sum of prompt, completion, and reasoning tokens
	TotalTokens int
}

// Model defines the contract for language model backends using Go 1.23+ iterators.
// The unified Generate method supports both streaming and blocking consumption patterns.
type Model interface {
	// Generate performs a request that yields Response chunks as an iterator.
	// For streaming, iterate over all chunks to get incremental updates.
	// For blocking, consume only the final response using Last() or similar helpers.
	//
	// Streaming usage:
	//   for resp, err := range model.Generate(ctx, messages) {
	//       if err != nil { return err }
	//       fmt.Print(resp.Message.Content) // Process each chunk
	//   }
	//
	// Blocking usage (helper required):
	//   resp, err := Last(model.Generate(ctx, messages))
	//   if err != nil { return err }
	//   fmt.Println(resp.Message.Content) // Process final message
	//   fmt.Println("Reasoning:", resp.Reasoning) // Access native reasoning
	//   fmt.Println("Finish reason:", resp.FinishReason) // Why generation stopped
	//   fmt.Printf("Tokens used: %d\n", resp.Usage.TotalTokens)
	//   if resp.Logprobs != nil {
	//       // Access token probabilities for confidence analysis
	//   }
	//
	// The iterator will yield:
	// - Multiple responses with incremental content (streaming mode)
	// - A single final response (blocking mode)
	// - The last yield will contain any error encountered
	//
	// Context cancellation is respected and will stop iteration.
	Generate(ctx context.Context, messages []message.Message) iter.Seq2[*Response, error]
}

// Last consumes an iterator and returns only the final response and error.
// This is the standard way to use Generate() in blocking/non-streaming mode.
//
// Example:
//
//	resp, err := model.Last(model.Generate(ctx, messages))
//	if err != nil {
//	    return err
//	}
//	fmt.Println(resp.Message.Content)
//	if resp.Reasoning != "" {
//	    fmt.Println("Reasoning:", resp.Reasoning)
//	}
func Last(seq iter.Seq2[*Response, error]) (*Response, error) {
	var lastResp *Response
	var lastErr error

	for resp, err := range seq {
		lastResp = resp
		if err != nil {
			lastErr = err
			break
		}
	}

	return lastResp, lastErr
}

// Collect gathers all responses from an iterator into a slice.
// The final error (if any) is returned separately.
//
// Example:
//
//	responses, err := model.Collect(model.Generate(ctx, messages))
//	if err != nil {
//	    return err
//	}
//	for _, resp := range responses {
//	    fmt.Println(resp.Message.Content)
//	}
func Collect(seq iter.Seq2[*Response, error]) ([]*Response, error) {
	responses := make([]*Response, 0)
	var lastErr error

	for resp, err := range seq {
		if err != nil {
			lastErr = err
			break
		}
		responses = append(responses, resp)
	}

	return responses, lastErr
}

// ToolAware defines models that support tool/function calling.
type ToolAware interface {
	// BindTools returns a copy of this model with the given tools configured.
	// The model will be able to call these tools during generation.
	BindTools(tools ...tool.Tool) Model
}

// StructuredOutput defines models that support structured output generation.
type StructuredOutput interface {
	// WithStructuredOutput returns a copy of this model configured to generate
	// output conforming to the provided JSON schema. The schema parameter should
	// be a map[string]any representing a JSON Schema definition.
	//
	// When using structured output:
	// - The model will be constrained to generate valid JSON matching the schema
	// - The response will typically be in the content of the returned message
	// - Invalid outputs may result in errors depending on the implementation
	//
	// Example schema:
	//  schema := map[string]any{
	//      "type": "object",
	//      "properties": map[string]any{
	//          "name": map[string]any{"type": "string"},
	//          "age":  map[string]any{"type": "integer"},
	//      },
	//      "required": []string{"name", "age"},
	//  }
	WithStructuredOutput(schema map[string]any) Model
}
